[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
remitano = "4pUWBrXKX1JXQv5fdn76LTGfYjvJqHzkPKxf3it86JPS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/ngmitam/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
